"""empty message

Revision ID: a239bcc59df4
Revises: f83bfe1d6cf7
Create Date: 2019-12-30 18:36:56.138508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a239bcc59df4'
down_revision = 'f83bfe1d6cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('project_code', sa.Integer(), nullable=True))
    op.drop_constraint('business_ibfk_1', 'business', type_='foreignkey')
    op.create_foreign_key(None, 'business', 'project', ['project_code'], ['id'])
    op.drop_column('business', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('project', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.create_foreign_key('business_ibfk_1', 'business', 'project', ['project'], ['id'])
    op.drop_column('business', 'project_code')
    # ### end Alembic commands ###
